<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260818110500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Align M1 index names and add the Doctrine Messenger transport table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER INDEX uniq_theme_institution RENAME TO UNIQ_766D7CC010405986');
        $this->addSql('ALTER INDEX uniq_user_email RENAME TO UNIQ_88BDF3E9E7927C74');
        $this->addSql('ALTER INDEX idx_membership_user RENAME TO IDX_86FFD285A76ED395');
        $this->addSql('ALTER INDEX idx_membership_institution RENAME TO IDX_86FFD28510405986');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER INDEX uniq_766d7cc010405986 RENAME TO uniq_theme_institution');
        $this->addSql('ALTER INDEX uniq_88bdf3e9e7927c74 RENAME TO uniq_user_email');
        $this->addSql('ALTER INDEX idx_86ffd285a76ed395 RENAME TO idx_membership_user');
        $this->addSql('ALTER INDEX idx_86ffd28510405986 RENAME TO idx_membership_institution');
    }
}
