<?php
declare(strict_types=1);
namespace App\Controller;
use App\Entity\Feedback;use App\Entity\SearchSynonym;use App\Entity\User;use App\Security\TenantRoleChecker;use App\Tenant\TenantContext;use Doctrine\ORM\EntityManagerInterface;use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;use Symfony\Component\Form\Extension\Core\Type\TextareaType;use Symfony\Component\Form\Extension\Core\Type\TextType;use Symfony\Component\HttpFoundation\Request;use Symfony\Component\HttpFoundation\Response;use Symfony\Component\Routing\Attribute\Route;use Symfony\Component\Security\Http\Attribute\IsGranted;
#[IsGranted('ROLE_USER')] final class AdminSearchFeedbackController extends AbstractController
{
 #[Route('/i/{institutionSlug}/admin/search-feedback',name:'tenant_admin_search_feedback',methods:['GET','POST'])] public function index(Request $request,TenantContext $context,TenantRoleChecker $roles,EntityManagerInterface $em):Response{$this->deny($roles);$institution=$context->requireInstitution();$form=$this->createFormBuilder()->add('term',TextType::class,['label'=>'Szakmai vagy elsődleges kifejezés'])->add('synonyms',TextareaType::class,['label'=>'Közérthető szinonimák','help'=>'Vesszővel vagy soronként elválasztva.'])->getForm();$form->handleRequest($request);if($form->isSubmitted()&&$form->isValid()){$values=preg_split('/[,\R]+/',(string)$form->get('synonyms')->getData())?:[];$em->persist(new SearchSynonym($institution,(string)$form->get('term')->getData(),$values));$em->flush();$this->addFlash('success','A keresési szinonima létrejött.');return $this->redirectToRoute('tenant_admin_search_feedback',['institutionSlug'=>$institution->getSlug()]);}return $this->render('admin/search_feedback/index.html.twig',['institution'=>$institution,'form'=>$form,'synonyms'=>$em->getRepository(SearchSynonym::class)->findBy(['institution'=>$institution],['term'=>'ASC']),'feedback'=>$em->getRepository(Feedback::class)->findBy(['institution'=>$institution],['createdAt'=>'DESC'],100)]);}
 #[Route('/i/{institutionSlug}/admin/search-feedback/synonym/{id}/delete',name:'tenant_admin_synonym_delete',methods:['POST'])] public function delete(string $id,Request $request,TenantContext $context,TenantRoleChecker $roles,EntityManagerInterface $em):Response{$this->deny($roles);$item=$em->getRepository(SearchSynonym::class)->find($id)??throw $this->createNotFoundException();if(!$item->getInstitution()->getId()->equals($context->requireInstitution()->getId()))throw $this->createAccessDeniedException();if(!$this->isCsrfTokenValid('delete_synonym_'.$id,$request->request->getString('_token')))throw $this->createAccessDeniedException();$em->remove($item);$em->flush();$this->addFlash('success','A szinonima törölve.');return $this->redirectToRoute('tenant_admin_search_feedback',['institutionSlug'=>$context->requireInstitution()->getSlug()]);}
 private function deny(TenantRoleChecker $roles):void{$user=$this->getUser();if(!$user instanceof User||(!in_array('ROLE_PLATFORM_ADMIN',$user->getRoles(),true)&&!$roles->hasRole($user,'ROLE_INSTITUTION_ADMIN')&&!$roles->hasRole($user,'ROLE_EDITOR')&&!$roles->hasRole($user,'ROLE_AUDITOR')))throw $this->createAccessDeniedException();}
}
