<?php
declare(strict_types=1);
namespace App\Controller;
use App\Entity\ContentTemplate;use App\Entity\InformationPage;use App\Entity\TemplateAdoption;use App\Entity\User;use App\Security\TenantRoleChecker;use App\Tenant\TenantContext;use Doctrine\ORM\EntityManagerInterface;use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;use Symfony\Component\HttpFoundation\Request;use Symfony\Component\HttpFoundation\Response;use Symfony\Component\Routing\Attribute\Route;use Symfony\Component\Security\Http\Attribute\IsGranted;
#[IsGranted('ROLE_USER')] final class AdminTemplateController extends AbstractController
{
 #[Route('/i/{institutionSlug}/admin/templates',name:'tenant_admin_templates',methods:['GET'])]public function index(TenantContext $context,TenantRoleChecker $roles,EntityManagerInterface $em):Response{$this->deny($roles);$institution=$context->requireInstitution();$adoptions=$em->getRepository(TemplateAdoption::class)->findBy(['institution'=>$institution]);$byTemplate=[];foreach($adoptions as $item)$byTemplate[(string)$item->getTemplate()->getId()]=$item;return $this->render('admin/templates/index.html.twig',['institution'=>$institution,'templates'=>$em->getRepository(ContentTemplate::class)->findAll(),'adoptions'=>$byTemplate]);}
 #[Route('/i/{institutionSlug}/admin/templates/{id}/adopt',name:'tenant_admin_template_adopt',methods:['POST'])]public function adopt(string $id,Request $request,TenantContext $context,TenantRoleChecker $roles,EntityManagerInterface $em):Response{$this->deny($roles);$institution=$context->requireInstitution();$template=$em->getRepository(ContentTemplate::class)->find($id)??throw $this->createNotFoundException();if(!$this->isCsrfTokenValid('adopt_template_'.$id,$request->request->getString('_token')))throw $this->createAccessDeniedException();$adoption=$em->getRepository(TemplateAdoption::class)->findOneBy(['institution'=>$institution,'template'=>$template]);if($adoption){$page=$adoption->getPage();$adoption->markUpdated();}else{$slug=$template->getTemplateKey();if($em->getRepository(InformationPage::class)->findOneBy(['institution'=>$institution,'slug'=>$slug]))$slug.='-sablon';$page=new InformationPage($institution,$template->getTitle(),$slug);$adoption=new TemplateAdoption($institution,$template,$page);$em->persist($page);$em->persist($adoption);}$page->setTitle($template->getTitle())->setSummary($template->getSummary())->setContent($template->getContent());$em->flush();$this->addFlash('success','A központi sablon piszkozatként átmásolva.');return $this->redirectToRoute('tenant_admin_crud_edit',['institutionSlug'=>$institution->getSlug(),'type'=>'page','id'=>$page->getId()]);}
 private function deny(TenantRoleChecker $roles):void{$user=$this->getUser();if(!$user instanceof User||(!in_array('ROLE_PLATFORM_ADMIN',$user->getRoles(),true)&&!$roles->hasRole($user,'ROLE_INSTITUTION_ADMIN')&&!$roles->hasRole($user,'ROLE_EDITOR')))throw $this->createAccessDeniedException();}
}
